name: code-editor-pipeline
networks:
  code-editor-network:
    driver: bridge

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      - backendport=5000
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
    ports:
      - "5173:5173"
    networks:
      - code-editor-network

  backend:
    build:
      context: ./backend
    environment:
      - appname=backend
      - exposeport=5000
      - executorport=1234
    # develop:
    #   watch:
    #     - action: sync
    #       path: ./backend
    #       target: /app
    expose:
      - "5000"
    ports:
      - "5000:5000"
    networks:
      - code-editor-network
  #   depends_on:
  #     - executor

  # executor:
  #   # internal service used by backend, no need to open it to the world...
  #   container_name: executor
  #   # restart: always
  #   build:
  #     context: ./execenv
  #   environment:
  #     - appname=executor
  #     - exposeport=1234
  #   # volumes:
  #   #   - ./execenv/.:/app
  #   develop:
  #     watch:
  #       - action: sync
  #         path: ./execenv
  #         target: /app
  #   expose:
  #     - "1234"
  #   # ports:
  #   #   - "5001:1234"
  #   cap_drop: # Drop all unnecessary capabilities
  #     - ALL
  #   security_opt:
  #     - no-new-privileges:true
  #   read_only: true
  #   mem_limit: 128m
  #   cpus: "0.5"
  #   networks:
  #     - code-editor-network